language: node_js
node_js:
- '0.10'
- '0.11'
deploy:
  provider: npm
  email: mark@segfawlt.net
  api_key:
    secure: LaXg09DLKsFtwqZR2s0K5bKjt7GeApIygDYW2SOoM0LtB00M0hoGCtoMEOPqyMlKyjDY9SjZtA/u4alc0QvG2cw3iPcGnc3+6FETeS94LUYztrfjVQNAHeufgBLFEnOtvFCf3HBXLnHpKttAcun9QkZ6YAI4R/ODKc0Zb8WZCvw=
  on:
    tags: true
    repo: hightail/node-jira-migrate
